### ISSUE TITLE
Call to private method Zend\Mvc\Console\View\ViewManager::getView() from context 'ZF\Rpc\Module'

### ISSUE THREAD

**Issue by waltertamboer** [zfcampus/zf-rpc#13]
I've also created an issue in zendframework/zend-mvc-console#14 - Not sure where to solve this problem so that's why I'm also creating the issue here.

**Comment by weckx** [comment]
I also have this issue here (Apigility application with some command line controllers) and when switching to zend-mvc-console this error started to happen.

I believe the fix should be here, maybe just check if the view manager is an instance of Zend\Mvc\View\Http\ViewManager before calling the _getView()_ method?

**Comment by weierophinney** [comment]
Update to zend-mvc-console 1.1.11:

```bash
$ composer require "zendframework/zend-mvc-console:^1.1.11"
```

That release updates `getView()` to have public visibility. I chose that route due to the fact that the zend-mvc `ViewManager` marks it public as well, making it the de facto public API.
